"""
Reads each .docx answer key in data/, extracts its text + tables in document
order, and asks Gemini to convert it into the structured rubric JSON.  Output
is written to rubrics/<rubric_id>.json for human review.

Needs GEMINI_API_KEY (or GOOGLE_API_KEY) to be sourced in the environment.
   uv run python scripts/extract_rubrics.py
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

from docx import Document
from docx.document import Document as DocumentType
from docx.oxml.ns import qn
from docx.table import Table
from docx.text.paragraph import Paragraph

from google import genai
from google.genai import types

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "rubrics"

# map each .docx to a separate id
# id need to be autogenerated when production
ASSIGNMENT_MAP: dict[str, str] = {
    "entry_microscopy": "Entry Microscopy for Training_With Data_Answers.docx",
    "entry_flow_cytometry": "Entry Flow Cytometry for Training_With Data_Answers.docx",
    "entry_western_blot": "Entry Western Blot for Training_With Data_Answers.docx",
    "hw_assignment_2026": "HW Assignment 2026_With Data_Answers.docx",
    "signal_transduction_1a": "Signal Transduction Pathway 1A_With Data_Answers (1).docx",
    "bn5101_week10": "BN5101_Week 10_Virtual Lab_ANS.docx",
}

DEFAULT_MODEL = "gemini-3.1-flash-lite"


def render_table(table: Table) -> str:
    """Render a docx table as a pipe-delimited block (header row + separator)."""
    rows = []
    for r in table.rows:
        rows.append([c.text.strip().replace("\n", " ") for c in r.cells])
    if not rows:
        return ""
    out = ["| " + " | ".join(rows[0]) + " |",
           "| " + " | ".join("---" for _ in rows[0]) + " |"]
    for row in rows[1:]:
        out.append("| " + " | ".join(row) + " |")
    return "\n".join(out)


def extract_docx(path: Path) -> str:
    """Flatten a .docx to text, walking paragraphs and tables in body order."""
    doc: DocumentType = Document(str(path))
    parts: list[str] = []
    for child in doc.element.body.iterchildren():
        if child.tag == qn("w:p"):
            text = Paragraph(child, doc).text.strip()
            if text:
                parts.append(text)
        elif child.tag == qn("w:tbl"):
            rendered = render_table(Table(child, doc))
            if rendered:
                parts.append("\n[TABLE]\n" + rendered + "\n[/TABLE]\n")
    return "\n".join(parts)


SYSTEM_PROMPT = r"""You convert a virtual cell-biology lab ANSWER KEY (extracted
from a .docx worksheet) into a single structured JSON rubric. These run on the
StarCellBio simulator. Emit ONLY the JSON object — no prose, no markdown fences.

Schema:
{
  "rubric_id": "<given to you>",
  "title": "<assignment title from the doc>",
  "course_code": "<e.g. BN3402, or null>",
  "views": ["microscopy" | "flow_cytometry" | "western_blot" | ...],
  "setup": {
    "samples": [], "channels": [], "treatments": [], "antibodies": [], "cell_lines": []
  },
  "questions": [
    {
      "id": "q1",
      "prompt": "<the question text, condensed>",
      "type": "categorical_map | numeric_with_tolerance | categorical_grid | ordered_sequence | free_text",
      "expected": <see type rules below>,
      "tolerance": <number or null>,
      "points": <number or null>
    }
  ],
  "free_text_rubric": [ "<verbatim grading bullets for free_text questions, incl. point allocations>" ]
}

Question type rules for "expected":
- categorical_map: object mapping each key to its expected category, e.g.
  {"blue": "Nucleus", "green": "Plasma Membrane", "red": "Cytoplasm"}
- numeric_with_tolerance: object of measurement -> number, e.g. {"G0/G1": 83, "S": 4, "G2/M": 13}.
  Put the +/- tolerance (as a number; if expressed as a percent like +/-5%, use 5) in "tolerance".
- categorical_grid: object keyed by row label; each value an object of column -> expected value, e.g.
  {"Protein A": {"location": "cytoplasm", "phosphorylation": "no"}, ...}
- ordered_sequence: an ordered array, e.g. ["Ligand","B","C","D","E","A","gene expression"]
- free_text: set "expected" to null and put the grading rationale/bullets in the
  top-level "free_text_rubric" array (verbatim, including any "[0.5 pt] ..." text).

Rules:
- Use the answer values shown in the doc's tables as the expected answers.
- Preserve point allocations where the doc states them; otherwise use null.
- Be faithful: do not invent samples, treatments, or answers not in the document.
- Output valid JSON only."""

FEWSHOT_DOC = """[Entry Microscopy training worksheet — abbreviated]
Identify the organelle labelled by each fluorophore in the three unknown samples.

[TABLE]
| Sample | Blue | Green | Red |
| --- | --- | --- | --- |
| Sample 1 | Nucleus | Plasma Membrane | Cytoplasm |
[/TABLE]
"""

FEWSHOT_JSON = json.dumps(
    {
        "rubric_id": "example_microscopy",
        "title": "Entry - Microscopy",
        "course_code": None,
        "views": ["microscopy"],
        "setup": {
            "samples": ["Sample 1"],
            "channels": ["blue", "green", "red"],
            "treatments": [],
            "antibodies": [],
            "cell_lines": [],
        },
        "questions": [
            {
                "id": "q1",
                "prompt": "Organelles labelled in Sample 1 (blue/green/red)",
                "type": "categorical_map",
                "expected": {
                    "blue": "Nucleus",
                    "green": "Plasma Membrane",
                    "red": "Cytoplasm",
                },
                "tolerance": None,
                "points": None,
            }
        ],
        "free_text_rubric": [],
    },
    indent=2,
)


def build_contents(rubric_id: str, doc_text: str) -> list[types.Content]:
    """One-shot example (user -> model), then the real document."""
    return [
        types.Content(
            role="user",
            parts=[types.Part(text=f"rubric_id: example_microscopy\n\nDocument:\n{FEWSHOT_DOC}")],
        ),
        types.Content(role="model", parts=[types.Part(text=FEWSHOT_JSON)]),
        types.Content(
            role="user",
            parts=[types.Part(text=f"rubric_id: {rubric_id}\n\nDocument:\n{doc_text}")],
        ),
    ]


def parse_json(text: str) -> dict:
    """Pull the JSON object out of the model response (tolerate stray fences)."""
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\n?", "", text)
        text = re.sub(r"\n?```$", "", text)
    return json.loads(text)


def extract_one(client: genai.Client, model: str, rubric_id: str) -> dict:
    src = DATA / ASSIGNMENT_MAP[rubric_id]
    if not src.exists():
        raise FileNotFoundError(src)
    doc_text = extract_docx(src)
    resp = client.models.generate_content(
        model=model,
        contents=build_contents(rubric_id, doc_text),
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            response_mime_type="application/json",
            max_output_tokens=32768,
        ),
    )
    rubric = parse_json(resp.text)
    u = resp.usage_metadata
    if u is not None:
        print(
            f"  tokens: in={u.prompt_token_count} "
            f"out={u.candidates_token_count} "
        )
    return rubric


def main() -> int:
    ap = argparse.ArgumentParser(description="Extract structured rubrics from .docx answer keys.")
    ap.add_argument("--model", default=os.environ.get("EXTRACT_MODEL", DEFAULT_MODEL))
    args = ap.parse_args()

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print(
            "ERROR: GEMINI_API_KEY not set.",
            file=sys.stderr,
        )
        return 1

    targets = list(ASSIGNMENT_MAP)

    OUT.mkdir(exist_ok=True)
    client = genai.Client(api_key=api_key)
    print(f"model: {args.model}\n")
    for rubric_id in targets:
        print(f"[{rubric_id}] <- {ASSIGNMENT_MAP[rubric_id]}")
        try:
            rubric = extract_one(client, args.model, rubric_id)
        except Exception as e:  # noqa: BLE001 - surface per-doc failures, keep going
            print(f"  FAILED: {type(e).__name__}: {e}", file=sys.stderr)
            continue
        dest = OUT / f"{rubric_id}.json"
        dest.write_text(json.dumps(rubric, indent=2) + "\n")
        nq = len(rubric.get("questions", []))
        print(f"  wrote {dest.relative_to(ROOT)}  ({nq} questions)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
